# Generated by Django 4.2.7 on 2026-03-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, choices=[('in_stock', 'В наличии'), ('on_the_way', 'Товар в пути'), ('new_2025', 'Новинка 2025 года'), ('new_arrival', 'Новое поступление'), ('best_offer', 'Лучшее предложение'), ('online_fitting', 'Онлайн-примерка')], max_length=20, null=True, verbose_name='Наличие'),
        ),
    ]
