# Generated by Django 4.2.7 on 2026-03-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена данной модели'),
        ),
    ]
