# Generated by Django 4.2.7 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tour_3d_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на 3D тур'),
        ),
    ]
