# Generated by Django 4.2.7 on 2026-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_add_tour_3d_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='map_point',
            field=models.CharField(blank=True, help_text='Координаты или идентификатор точки на карте. Не отображается на сайте.', max_length=500, verbose_name='Точка на карте'),
        ),
    ]
